# Generated by Django 3.1.7 on 2021-05-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210504_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='network.Like'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='reactions',
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(to='network.Reaction'),
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='likes',
        ),
        migrations.AddField(
            model_name='reaction',
            name='likes',
            field=models.ManyToManyField(to='network.Like'),
        ),
    ]
