# Generated by Django 3.1.7 on 2021-05-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210506_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='reply',
            field=models.CharField(default='', max_length=250),
        ),
    ]
