# Generated by Django 3.1.7 on 2021-05-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_reaction_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='network.Like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='network.Reaction'),
        ),
    ]
