# Generated by Django 3.1.7 on 2021-06-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
