# Generated by Django 3.1.7 on 2021-06-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_follower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followedby',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
