# Generated by Django 3.1.7 on 2021-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(blank=True, to='auctions.Bid'),
        ),
    ]
