# Generated by Django 3.1.7 on 2021-03-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(blank=True, max_length=250, to='auctions.Comment'),
        ),
    ]
